import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {getCheckeredClass} from "@/shared/ui/Container/CheckeredContainer";
import {ToastsHost} from "@/shared/ui/Toast";
import "../globals.css";
import {Providers} from "@/providers";
import {ModalsHost} from "@/shared/ui/Modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased [background-size:50px_50px] ${getCheckeredClass()}`}
      >
        <Providers>
          {children}
          <ModalsHost/>
          <ToastsHost/>
        </Providers>
      </body>
    </html>
  );
}
